language: node_js
dist: trusty
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
    - functions/node_modules
notifications:
  email: false
node_js:
  - '7.5'
#before_script:
#  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
before_deploy:
  - cd functions/
  - yarn
  - cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token: "$FIREBASE_TOKEN"
  message: "Deployed by Travis CI"
